# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - redalign

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  solution_file: 'RedAlign.Portal.Service.sln'
  nuget_feed_name: 'kevinvarga'
  nuget_feed_source: 'https://pkgs.dev.azure.com/kevinvarga/_packaging/kevinvarga/nuget/v3/index.json'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Auth NuGet
        run: dotnet nuget add source ${{ env.nuget_feed_source }} --name ${{ env.nuget_feed_name }} --username az --password ${{ secrets.AZURE_DEVOPS_TOKEN }}

      - name: Restore NuGet Packages
        run: dotnet restore ${{ env.solution_file_path }}

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish RedAlign.Portal.Service.sln -c Debug  -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'redalign'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2392DCD8D9FF4A17990761C61E3EBDA7 }}
          package: .

  build_react:
      name: Build and deploy React
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: npm install and build
        run: |
          npm install
          npm run build
        working-directory: portal

  deploy_react:
    runs-on: windows-latest
    needs: build_react
    
    steps:
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: 'redalign'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2392DCD8D9FF4A17990761C61E3EBDA7 }}
          package: portal/build
